import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  Building2,
  Calculator,
  Briefcase,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  CircleDollarSign,
  Coins,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  File,
  FileText,
  FileCheck,
  Filter,
  GitBranch,
  Hash,
  HelpCircle,
  Home,
  Hotel,
  Info,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  MoreVertical,
  Palette,
  Percent,
  PieChart,
  Pencil,
  Plug,
  Plus,
  Receipt,
  ReceiptText,
  RefreshCw,
  Ruler,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  Sliders,
  Star,
  Target,
  Trash2,
  TrendingUp,
  Unlock,
  Upload,
  User,
  UserCircle,
  Users,
  Wallet,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon
} from "lucide-react";

/** Semantic icon names — not tied to any library export name. */
export const ICON_NAMES = [
  "dashboard",
  "properties",
  "units",
  "tenants",
  "applicants",
  "leases",
  "invoices",
  "payments",
  "expenses",
  "financials",
  "statements",
  "reports",
  "settings",
  "profile",
  "search",
  "notification",
  "menu",
  "close",
  "back",
  "more",
  "view",
  "edit",
  "delete",
  "save",
  "send",
  "download",
  "upload",
  "add",
  "filter",
  "calendar",
  "wallet",
  "rent",
  "income",
  "expense",
  "status",
  "property",
  "unit",
  "lease",
  "tenant",
  "document",
  "pdf",
  "lock",
  "unlock",
  "warning",
  "success",
  "cancel",
  "logout",
  "documents",
  "messages",
  "calculators",
  "email",
  "open",
  "help",
  "palette",
  "plug",
  "shield",
  "sliders",
  "bell",
  "chevronDown",
  "activity",
  "percent",
  "cap-rate",
  "star",
  "tools",
  "secure",
  "fast",
  "scenarios",
  "accurate",
  "leaseCancel",
  "void",
  "maintenance",
  "info",
  "portfolio",
  "verified",
  "hash"
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Central registry: semantic name → lucide-react component. */
export const iconMap: Record<IconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  properties: Home,
  property: Home,
  units: Building2,
  unit: Building2,
  tenants: Users,
  tenant: User,
  applicants: Users,
  leases: FileText,
  lease: FileText,
  invoices: ReceiptText,
  payments: CreditCard,
  expenses: Receipt,
  expense: Receipt,
  financials: CreditCard,
  statements: FileText,
  reports: BarChart3,
  settings: Settings,
  profile: UserCircle,
  search: Search,
  notification: Bell,
  menu: Menu,
  close: X,
  back: ArrowLeft,
  more: MoreVertical,
  view: Eye,
  edit: Pencil,
  delete: Trash2,
  save: Check,
  send: Send,
  download: Download,
  upload: Upload,
  add: Plus,
  filter: Filter,
  calendar: Calendar,
  wallet: Wallet,
  rent: CircleDollarSign,
  income: TrendingUp,
  status: BadgeCheck,
  document: File,
  pdf: FileText,
  lock: Lock,
  unlock: Unlock,
  warning: AlertTriangle,
  success: CheckCircle2,
  cancel: X,
  logout: LogOut,
  documents: File,
  messages: MessageSquare,
  calculators: Calculator,
  email: Mail,
  open: ExternalLink,
  help: HelpCircle,
  palette: Palette,
  plug: Plug,
  shield: Shield,
  sliders: Sliders,
  bell: Bell,
  chevronDown: ChevronDown,
  activity: Activity,
  percent: Percent,
  "cap-rate": Percent,
  star: Star,
  tools: LayoutGrid,
  secure: Shield,
  fast: Zap,
  scenarios: GitBranch,
  accurate: CheckCircle2,
  leaseCancel: XCircle,
  void: Trash2,
  maintenance: Wrench,
  info: Info,
  portfolio: Briefcase,
  verified: FileCheck,
  hash: Hash
};

export function getIconComponent(name: IconName): LucideIcon {
  return iconMap[name];
}

export function isIconName(value: string): value is IconName {
  return (ICON_NAMES as readonly string[]).includes(value);
}

/** Calculator slug → semantic icon (used by calculator hub / homepage). */
export const calculatorSlugIconMap: Record<string, IconName> = {
  "buy-vs-rent": "lease",
  "transfer-bond-costs": "open",
  "monthly-payment": "calculators",
  ltv: "property",
  "square-footage": "unit",
  "cash-flow": "wallet",
  noi: "reports",
  "operating-expense-ratio": "expense",
  "short-term-rental": "property",
  "cash-on-cash-return": "rent",
  "cap-rate": "percent",
  irr: "income",
  dscr: "status",
  dcf: "reports",
  grm: "property",
  "rent-to-cost-ratio": "percent",
  brrrr: "calculators",
  "70-rule": "status",
  "flip-profit": "income",
  "wholesale-profit": "payments",
  "rehab-cost": "expense"
};

// Slugs that need dedicated lucide icons not covered by semantic names
const CALCULATOR_EXTRA_ICONS: Record<string, LucideIcon> = {
  "buy-vs-rent": KeyRound,
  "transfer-bond-costs": ArrowLeftRight,
  "short-term-rental": Hotel,
  "operating-expense-ratio": PieChart,
  dcf: LineChart,
  grm: Building2,
  brrrr: RefreshCw,
  "70-rule": Target,
  "flip-profit": Coins,
  "wholesale-profit": Banknote,
  "rehab-cost": Wrench,
  "square-footage": Ruler,
  dscr: Scale
};

export function getCalculatorLucideIcon(slug: string): LucideIcon {
  const extra = CALCULATOR_EXTRA_ICONS[slug];
  if (extra) return extra;
  const name = calculatorSlugIconMap[slug];
  if (name && name in iconMap) return iconMap[name as IconName];
  return Calculator;
}
